version: '3.8'

services:
  api_gateway1:
    build:
      context: ./api-gateway
    container_name: api_gateway1
    ports:
      - "3001:3000"

  api_gateway2:
    build:
      context: ./api-gateway
    container_name: api_gateway2
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_gateway1
      - api_gateway2
